name: Publish Mobile Update via EAS

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Login to EAS
        run: npx eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Publish update
        run: npx eas update --branch production
